default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 3306
  username: root
  password: 123123abc
  host: 127.0.0.1

development:
  <<: *default
  username: root
  password: 123123abc
  database: users_development
  host: 127.0.0.1
test:
  <<: *default
  database: users_test
production:
  <<: *default
  database: users_production
  username: users
  password: <%= ENV["USERS_DATABASE_PASSWORD"] %>
